name: Build and test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: swift test
      - name: Build app bundle
        run: ./Scripts/build_app.sh
